### ISSUE TITLE
Server-side code to create ordinations in GEE has memory issues

### ISSUE THREAD

**Issue by grovduck** [lemma-osu/gee-knn-python#3]
As of e8eaddc337b248b8ac7b393bdcd7a50dc7dfe4e6, we create the ordinations used in this package using GEE functions (including linear algebra functions) like `ee.Array.matrixQRDecomposition` and `ee.Array.matrixSolve`.  In testing with partners through the [servir-mekong-knn](https://github.com/lemma-osu/servir-mekong-knn/tree/fb-add-classes) project, we have found that with a high number of features (e.g., > 10000), that some ordination methods (specifically `GNN` and `MSN`) will fail to complete even when exported.  Our working hypothesis is that GEE is recalculating the ordination for each node in its distributed workflow and that this can lead to memory issues when using these linear algebra functions.

Furthermore, the training needs only to be done one time and then the relevant data to provide the transformation of target data and reference data can be distributed to the nodes for processing.  In my naive way of thinking, when a GEE tile is being evaluated, it should only need three pieces of information to perform the nearest neighbor search:
* The raw covariate data (stored as bands in an `ee.Image`) for that tile
* Optionally, the arrays that will provide the coefficients/normalization needed to transform the covariate data into an estimator's feature space. (Note that the `Raw` method does no transformation of the data).
* The feature space coordinates of the reference data that will serve as candidate neighbors for each estimator.

The size of the transformation arrays should be very small and will only vary slightly with the number of covariates used (or number of components retained for `GNN` and `MSN`).  The coordinate arrays will linearly scale with the number of neighbors used, but should be small relative to the size of the ee.Image tile being passed.

As of now, and with the advancement of [sknnr](https://github.com/lemma-osu/scikit-learn-knn-regression), we are evaluating the possibility of this workflow for the estimators:
1. During the `train` step, convert the passed (server-side) `ee.FeatureCollection` to a client-side version of this.
2. Use the scikit-learn transformers available in `sknnr` for each method to get the needed transformation arrays as well as create the transformed coordinates of the reference data.
3. Convert these two pieces of information *back* into GEE (server-side) objects and run each estimator's `predict` and `predict_fc` methods on GEE.

The introduction of `sknnr` into this workflow should provide two distinct benefits:

1. Have a single source for all ordination methods
2. Provide the mechanism to create the client-side transformations needed to "interrupt" the server workflow so that memory issues are minimized.

**Comment by grovduck** [comment]
Email conversation with @aazuspan that informs our thinking and background on this issue:

@grovduck wrote:

I just want to make sure I'm thinking about client-server stuff in GEE correctly with regard to how we plan to run gee-knn.  Here's a really simple script:

https://code.earthengine.google.com/2a6214cfde245fe81bd59542ab1dbd32

The first print statement is completely server-side: create a feature, then create a constant image from that feature, add it to another constant image and then print out the invocation string.

The second print statement interrupts the flow by getting the value from the feature first using .getInfo and then uses that (client-side) value in the same workflow as above.  The invocation string shows that the feature was first evaluated before being put in the ee.Image.constant call.

So, for gee-knn, I'm planning that the call to `train` (using GEE's vocabulary) will pass a (server-side) feature collection which first gets evaluated as a client-side pseudo-feature collection, uses `sknnr` to set the transformation, and then creates server-side objects needed to do the transformations on `ee.FeatureCollection` (in the case of `predict_fc`) and `ee.Image` (in the case of `predict`).  My thought is that by doing all the transformation client-side, I will avoid the expensive linear algebra that was causing memory issues.  The tile processing should only need the actual image data, the transformation arrays (small), and the scores of the plots in the transformed space (small-ish).  

Does all this make sense to you?

**Comment by grovduck** [comment]
@aazuspan wrote:

Yeah, I follow your logic, and it seems like a clever workaround to the memory issues you've run into with applying the transforms server side.

There are certainly some limitations that might give you trouble with larger feature collections, both moving server-to-client and possibly client-to-server (max 5000 features, data size limits, slow performance, memory issues if the FC requires a lot of computation to generate), but some of those can probably be managed by chunking large feature collections and parallelizing. 

Do you plan to allow training with a client-side dataset? If your FC was too large to compute on the fly, maybe that could be a workaround by exporting to drive first and then loading in from a dataframe?

**Comment by grovduck** [comment]
@grovduck wrote:



> There are certainly some limitations that might give you trouble with larger feature collections, both moving server-to-client and possibly client-to-server (max 5000 features, data size limits, slow performance, memory issues if the FC requires a lot of computation to generate), but some of those can probably be managed by chunking large feature collections and parallelizing.

Yes, I was thinking that the server-to-client feature collection conversion was going to be pretty painful, but in early tests, it didn’t seem to do too badly, even when I had to do multiple grabs (i.e., the number of features was > 5000).  I might need to lean on you for some help parallelizing this process – I’m not sure I’d know how to do that efficiently. 

> Do you plan to allow training with a client-side dataset? If your FC was too large to compute on the fly, maybe that could be a workaround by exporting to drive first and then loading in from a dataframe?

Good question about the client-side dataset.  I had been briefly thinking about that yesterday but I hadn’t quite come up with how to do it.  Your suggestion is a good one.

To get even slightly more complicated, in the work we’re doing with the SERVIR Mekong group, we’re really trying to characterize uncertainty in land cover mapping.  We’re conceiving of uncertainty coming from three different sources:
1. the neighbors themselves (each neighbor may predict a different outcome)
2. the NN method used
3. slight perturbations (or realizations) of the environmental covariates going in.  

Right now, that whole logic is sitting in the [servir-mekong-knn](https://github.com/lemma-osu/servir-mekong-knn/tree/fb-add-classes) repo which basically wraps this whole process.  One of the steps there is to create the environmental matrix from each combination of spatial realizations and store that as a feature collection.  Because that was the format of data I was working with (i.e., server-side feature collections), I hadn’t given much thought to client-side versions.

**Comment by aazuspan** [comment]
> Yes, I was thinking that the server-to-client feature collection conversion was going to be pretty painful, but in early tests, it didn’t seem to do too badly, even when I had to do multiple grabs (i.e., the number of features was > 5000).

That's reassuring! I think one of the slower and more data-intensive parts of grabbing feature collections is when you're dealing with complex geometries, which shouldn't be a problem if you're just grabbing points (and presumably you don't even need the geometry client-side anyways).

>  I might need to lean on you for some help parallelizing this process – I’m not sure I’d know how to do that efficiently.

I've experimented with this some in the past and had decent luck with just splitting collections into smaller chunks and making parallel `getInfo` calls. I think I benchmarked that against `ee.FeatureCollection.getDownloadURL` and found it performed better, but I'd have to dig up some old code to confirm that. I don't have much experience with [`ee.data.computeFeatures`](https://developers.google.com/earth-engine/apidocs/ee-data-computefeatures), so that might be worth experimenting with as well.

> Because that was the format of data I was working with (i.e., server-side feature collections), I hadn’t given much thought to client-side versions.

Makes total sense! I imagine most use cases would start with a server-side FC.

**Comment by grovduck** [comment]
> I've experimented with this some in the past and had decent luck with just splitting collections into smaller chunks and making parallel `getInfo` calls. I think I benchmarked that against `ee.FeatureCollection.getDownloadURL` and found it performed better, but I'd have to dig up some old code to confirm that. I don't have much experience with [`ee.data.computeFeatures`](https://developers.google.com/earth-engine/apidocs/ee-data-computefeatures), so that might be worth experimenting with as well.

I'd be curious to see how you've done this.  It looks like you reference it at https://github.com/lemma-osu/naip-cnn/issues/1, but I'm not sure I see the code?  I've got a sample feature collection with 50,000 points that I'd like to experiment with.  

I think I've hit a wall and have been using `ee.FeatureCollection.toList()` because that's the only way I can think to batch the records, but that only returns the features as a list and you lose all the top level properties like `type`, `columns`, `version`, etc. of the feature collection.  `ee.FeatureCollection.limit()` doesn't give the flexibility of providing an offset and the only other way I could think about batching was to use `ee.FeatureCollection.filter` but it wasn't clear what to filter on!

Note that it's probably not critical that I have access to anything *but* the features, but I'd like to figure out how to bring the entire object client-side (in batches) if possible.

**Comment by aazuspan** [comment]
Looking at my old code, I came to the same conclusion you did - there was no way to chunk the FC without first converting to a list. If you need those top-level properties, I imagine there's a relatively efficient solution where you grab the features as chunked lists and make a separate request to get the properties (maybe just `fc.limit(0).getInfo()`?).

I was exploring this as part of a package I was developing to standardize moving data between EE and client-side libraries like GeoPandas and Xarray, but I never got it to a publicly releasable state. I'm not sure it will be much use to you, but I'll add you as a collaborator on the private repo so you can take a look at the [solution I landed on](https://github.com/aazuspan/eeio/blob/2a2138b99db0eb9fe1bfa41a44074f6c4abe6d89/eeio/featurecollection.py#L38-L71).

Regarding `getInfo` vs. `getDownloadURL`, I made this note:

>  This implementation uses `getInfo` instead of `getDownloadURL`. The latter is generally faster, but it has unpredictable limitations that depend on geometry complexity and prevent effective chunking.

I don't remember the exact details, but I do recall that `getDownloadURL` would fail if a chunk contained too much data, which was difficult to predict and meant that different FCs would have different max chunk sizes.

**Comment by grovduck** [comment]
> I was exploring this as part of a package I was developing to standardize moving data between EE and client-side libraries like GeoPandas and Xarray, but I never got it to a publicly releasable state. I'm not sure it will be much use to you, but I'll add you as a collaborator on the private repo so you can take a look at the [solution I landed on](https://github.com/aazuspan/eeio/blob/2a2138b99db0eb9fe1bfa41a44074f6c4abe6d89/eeio/featurecollection.py#L38-L71).

Oh my goodness, your code is so elegant.  So much fun to read!  I admit it took me a full 1.5 hours to figure out how the accessors work, but so cool to see.  

For now, if it's OK with you, I'll probably stick to lifting some of the guts of what you have in `FeatureCollection.to_geojson` (especially the `joblib` stuff - that's awesome!).  If you do end up releasing `eeio` at some point, I'd definitely transition to using that instead.  Thanks so much for sharing.  Let me know if you have any reservations about this.

**Comment by aazuspan** [comment]
You're more than welcome to pull out anything you find useful! I got distracted by other projects and don't have any plans to finish it at this point.

**Comment by grovduck** [comment]
Closed by #4.
